

DELETE FROM CALIFICACIONENTITY;
DELETE FROM FUNCIONENTITY;
DELETE FROM CRITICOENTITY;
DELETE FROM CRITICOENTITY_FESTIVALENTITY;
DELETE FROM FESTIVALENTITY;
DELETE FROM PELICULAENTITY;
DELETE FROM PELICULAENTITY_CRITICOENTITY;
DELETE FROM RESERVAENTITY_FUNCIONENTITY;
DELETE FROM RESERVAENTITY;
DELETE FROM SALAENTITY;
DELETE FROM SILLAENTITY;
DELETE FROM TEATROENTITY;
DELETE FROM TEATROENTITY_FESTIVALENTITY;
DELETE FROM USUARIOENTITY;
