DELETE FROM CALIFICACIONENTITY;
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (1, 'BCM Cosmetique SAS', 3.7, 100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (2, 'Major Pharmaceuticals', 3.6, 200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (3, 'Safeway', 4.6, 300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (4, 'Rebel Distributors Corp', 1.8, 400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (5, 'King Bio Inc.', 2.6, 500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (6, 'Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC', 1.6, 600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (7, 'Major Pharmaceuticals', 3.9, 700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (8, 'Allergy Laboratories, Inc.', 4.9, 800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (9, 'Mylan Pharmaceuticals Inc.', 4.0, 900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (10, 'Natureplex LLC', 2.3, 1000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (11, 'Roxane Laboratories, Inc.', 3.1, 1100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (12, 'Publix Super Markets', 4.4, 1200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (13, 'Baxter Healthcare Corporation', 4.2, 1300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (14, 'UCB, Inc.', 4.7, 1400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (15, 'Qualitest Pharmaceutical, Inc.', 2.9, 1500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (16, 'Aurobindo Pharma Limited', 3.9, 1600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (17, 'Coty US LLC', 4.5, 1700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (18, 'Watson Laboratories, Inc.', 3.2, 1800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (19, 'REMEDYREPACK INC.', 3.0, 1900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (20, 'Ventura Corporation LTD', 2.7, 2000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (21, 'Exelan Pharmaceuticals, Inc.', 3.6, 2100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (22, 'Chain Drug Consortium, LLC', 4.2, 2200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (23, 'Organon Pharmaceuticals USA', 2.2, 2300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (24, 'PD-Rx Pharmaceuticals, Inc.', 1.0, 2400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (25, 'Nicobrand LTD', 4.3, 2500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (26, 'Janssen Pharmaceuticals, Inc.', 2.1, 2600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (27, 'Nelco Laboratories, Inc.', 1.9, 2700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (28, 'Physicians Total Care, Inc.', 1.6, 2800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (29, 'Vansen Pharma Inc.', 1.7, 2900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (30, 'McKesson', 1.1, 3000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (31, 'Nelco Laboratories, Inc.', 1.8, 3100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (32, 'Hospira, Inc.', 1.4, 3200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (33, 'Nelco Laboratories, Inc.', 2.4, 3300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (34, 'Walgreen Co', 3.0, 3400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (35, 'Rebel Distributors Corp', 1.5, 3500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (36, 'AvKARE, Inc.', 3.0, 3600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (37, 'ALK-Abello, Inc.', 1.3, 3700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (38, 'Major Pharmaceuticals', 1.0, 3800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (39, 'Nelco Laboratories, Inc.', 2.7, 3900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (40, 'Topco Associates LLC', 1.9, 4000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (41, 'Professional Disposables International, Inc.', 3.8, 4100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (42, 'Ferndale Laboratories, Inc.', 2.0, 4200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (43, 'Lake Erie Medical DBA Quality Care Products LLC', 4.5, 4300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (44, 'HyVee Inc', 1.4, 4400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (45, 'Zydus Pharmaceuticals (USA) Inc.', 1.5, 4500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (46, 'Meditrend, Inc. DBA Progena Professional Formulations', 3.7, 4600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (47, 'Johnson & Johnson Consumer Products Company, Division of Johnson & Johnson Consumer Companies, Inc.', 3.2, 4700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (48, 'Lannett Company, Inc.', 4.4, 4800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (49, 'Apotex Corp.', 3.6, 4900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (50, 'Nelco Laboratories, Inc.', 3.5, 5000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (51, 'Colgate Oral Pharmaceuticals, Inc.', 3.3, 5100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (52, 'Jerome Stevens Pharmaceuticals, Inc.', 2.2, 5200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (53, 'Volume Distributors, Inc.', 4.8, 5300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (54, 'Meijer Distribution Inc', 1.1, 5400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (55, 'HOMEOLAB USA INC', 4.2, 5500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (56, 'Clinical Solutions Wholesale', 4.1, 5600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (57, 'Purdue Products LP', 2.1, 5700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (58, 'Antigen Laboratories, Inc.', 2.1, 5800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (59, 'Cardinal Health', 3.9, 5900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (60, 'Walgreens', 1.0, 6000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (61, 'Sun Pharma Global FZE', 1.4, 6100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (62, 'Lake Erie Medical DBA Quality Care Products LLC', 4.2, 6200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (63, 'Coria Laboratories, LTD', 1.3, 6300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (64, 'Roerig', 3.7, 6400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (65, 'Walgreen Company', 1.7, 6500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (66, 'Jafra Cosmetics International Inc', 2.0, 6600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (67, 'Clinical Solutions Wholesale', 3.5, 6700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (68, 'Nephron Pharmaceuticals Corporation', 1.1, 6800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (69, 'Cardinal Health', 3.9, 6900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (70, 'Apotheca Company', 1.1, 7000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (71, 'AMWAY CORP.', 1.5, 7100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (72, 'Mylan Pharmaceuticals Inc.', 2.6, 7200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (73, 'Medline Industries, Inc.', 3.5, 7300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (74, 'Med-Health Pharma, LLC', 1.7, 7400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (75, 'ALK-Abello, Inc.', 2.2, 7500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (76, 'The Mentholatum Company', 1.5, 7600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (77, 'General Distributing Company', 1.3, 7700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (78, 'Kramer Novis', 2.5, 7800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (79, 'Procter and Gamble Manufacturing Company', 5.0, 7900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (80, 'Contract Pharmacy Services-PA', 1.2, 8000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (81, 'NorthStar Rx LLC', 3.5, 8100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (82, 'Amerisource Bergen', 2.2, 8200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (83, 'REMEDYREPACK INC.', 3.1, 8300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (84, 'LIVE BETTER (The Great Atlantic & Pacific Tea Company)', 1.6, 8400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (85, 'AMOREPACIFIC', 1.6, 8500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (86, 'Carlsbad Technology, Inc.', 1.1, 8600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (87, 'McKesson', 2.4, 8700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (88, 'REMEDYREPACK INC.', 4.8, 8800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (89, 'McKesson Packaging Services a business unit of McKesson Corporation', 4.0, 8900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (90, 'REMEDYREPACK INC.', 1.5, 9000);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (91, 'Qualitest Pharmaceuticals', 1.1, 9100);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (92, 'Geri-Care Pharmaceuticals, Corp', 1.6, 9200);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (93, 'Newton Laboratories, Inc.', 1.2, 9300);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (94, 'Certus Medical, Inc.', 1.3, 9400);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (95, 'Shopko Stores Operating Co., LLC', 4.0, 9500);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (96, 'McKesson Contract Packaging', 2.3, 9600);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (97, 'REMEDYREPACK INC.', 4.5, 9700);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (98, 'Ferring Pharmaceuticals Inc.', 1.2, 9800);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (99, 'Novartis Consumer Health, Inc.', 2.8, 9900);
insert into calificacionentity (id, comentario, puntaje, usuario_id) values (100, 'State of Florida DOH Central Pharmacy', 1.1, 10000);
